function Conclusion() {
    return (
        <>
            <h1>Conclusion</h1>
            <p>“Machines may be made of steel and silicon, but the soul of robotics is in the creativity of its creators” —Hiroshi Ishiguro. I wondered how I could create a machine of steel with brains of silicon but a soul of my brain and with a function of being useful to anyone, that caused my inquiry question to be one simple question, “How can I create a robot arm that can help anyone?” Using coding, machining, circuitry, and soldering I wanted to create a robot arm that was useful but also taught me robotics.</p>
	        <p>I started out the project as just a boy with skills and a dream. I watched a video about someone making a robot arm (https://www.youtube.com/watch?v=5toNqaGsGYs) and I started to wonder how to make my own—I wondered how I could turn my skills into a real machine. And then I began to research, I began to wonder and let the ideas flow, I mentally debated materials and reasoned how to wire the components. I learned things like designs, and in these first two months I began to shop around and look at wonderful components and marvelous technology. I felt like a kid in a candy store. As I began to receive my parts and learn my assembly plan I led into the next two months. But even then I kept doing designs in my mind and I kept thinking about how I could have just one more feature within.</p>
	        <p>As 3d printers layed down layer lines I began to fabricate my robot arm and I started to learn how to program it. In this period of time I was soldering and I designed things like forearms and shoulders like pictured in the nearby image and I started to adjust my designs to fit my components and I tested. While I started to wire things up and run some code I saw smoke rise from my power supply and I knew I needed to change my approach. So I kept innovating and I kept letting my neurons fire to solve problems that were new to me but not foreign as I worked with things I knew like 3d printing but in ways I hadn't tried before to make a full fledged arm.  I began to learn how to make code on the ESP32 and I started learning what it's like to wire up a servo motor.</p>
	        <p>Soon, the final few months of my project rolled in and I went from fabricating new ideas to deciding what I could do in the remaining time. I fixed the problem of a bad power supply by hooking up power to the ESP32 and directly 12v of DC to the stepper motor. I had to abandon the idea of inverse kinematics due to the sheet amount of math I needed which was beyond my current knowledge. I had to also buy a new stepper motor controller which made the stepper motors only work right near the end of the project. I decided upon using three different dials to control the arm and my ideas started to form into a larger assembly. I went from a young boy with skills and an idea to a man with more skills in more domains and a robot arm—seeing my skills turn into something greater was amazing, it felt like a superpower.</p>
	        <p>In conclusion, it took a lot of effort and was very hard but I finished strong with the project and I enjoyed doing it. Research was hard to find with robotics being such a complicated field but I did my best and had fun. The answer to my inquiry question was, I can create this robot arm by using my skills and learning new skills to fabricate a robot arm and then program it. My project didn't have a huge impact, it didn't change Ventura, but it gave me a set of skills that will be amazing for my future and for my career.</p>
        </>
    )
}

export default Conclusion;